# -*- coding: utf-8 -*-
"""
BORRADORES DE ARTÍCULOS — Perspectivas
Cada artículo tiene versión ES y EN con la MISMA estructura de bloques.
Tipos de bloque: ('h2', texto) · ('p', html) · ('ul', [html, ...]) · ('quote', texto) · ('media', 'video'|'infografia'|'galeria')
IMPORTANTE: son borradores. Revisar cada dato legal antes de publicar.
"""

MESES_ES = ["", "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"]
MESES_EN = ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

ARTICULOS = [
# ---------------------------------------------------------------- 1
dict(
    slug="ai-governance-mexico", icon="fa-robot", cat=("AI & Tech", "AI & Tech"), fecha=(2026, 1, 13), mins=5,
    titulo=("AI Governance: el nuevo desafío regulatorio para las empresas mexicanas",
            "AI Governance: the new regulatory challenge for Mexican companies"),
    deck=("La Inteligencia Artificial ya opera dentro de las empresas mexicanas. La pregunta incómoda es quién la gobierna.",
          "Artificial Intelligence already operates inside Mexican companies. The uncomfortable question is who governs it."),
    esencial=(["No existir una ley general de IA no significa que no haya reglas aplicables.",
               "Un programa efectivo se apoya en transparencia, responsabilidad, auditoría y cumplimiento.",
               "Los inversionistas ya preguntan por AI Governance en la debida diligencia."],
              ["The absence of a general AI law does not mean there are no applicable rules.",
               "An effective program rests on transparency, accountability, auditing and compliance.",
               "Investors are already asking about AI governance during due diligence."]),
    es=[("h2", "El vacío regulatorio actual"),
        ("p", "A la fecha de este artículo, México no cuenta con una ley general de Inteligencia Artificial. Eso no significa que opere sin reglas: la protección de datos personales, la protección al consumidor, la propiedad intelectual y la regulación sectorial ya alcanzan a los sistemas que automatizan decisiones."),
        ("p", "A nivel internacional el panorama es más concreto. El AI Act de la Unión Europea adopta un enfoque basado en riesgo con obligaciones escalonadas, y una empresa mexicana que ofrezca productos o servicios en ese mercado puede quedar bajo su alcance."),
        ("media", "video"),
        ("h2", "Los cuatro pilares de un AI Governance efectivo"),
        ("p", "Un programa sólido no empieza con una política de veinte páginas, sino con cuatro decisiones prácticas:"),
        ("ul", ["<strong>Transparencia:</strong> documentar qué modelos se usan, con qué datos se entrenan y qué decisiones automatizan.",
                "<strong>Responsabilidad:</strong> definir quién responde cuando un sistema falla o discrimina.",
                "<strong>Auditoría:</strong> establecer revisiones periódicas, internas y externas.",
                "<strong>Cumplimiento:</strong> alinear cada implementación con los marcos aplicables."]),
        ("quote", "La pregunta ya no es si tu empresa necesita AI Governance, sino cuándo empieza a construirlo."),
        ("h2", "El costo de no actuar"),
        ("p", "Adoptar IA sin gobierno interno expone a la empresa a sanciones, pero también a la <strong>pérdida de confianza del cliente</strong>, a <strong>frenos en rondas de inversión</strong> y a <strong>riesgos reputacionales</strong> difíciles de revertir."),
        ("h2", "Por dónde empezar"),
        ("p", "Con un inventario de los sistemas de IA en uso, una clasificación por nivel de riesgo, responsables designados y alineación con estándares como ISO/IEC 42001 y el NIST AI Risk Management Framework. En BLIC acompañamos a empresas tech y startups en ese recorrido.")],
    en=[("h2", "The current regulatory gap"),
        ("p", "As of this article, Mexico has no general Artificial Intelligence law. That does not mean AI operates without rules: personal data protection, consumer protection, intellectual property and sector-specific regulation already reach systems that automate decisions."),
        ("p", "Internationally the picture is more concrete. The European Union’s AI Act takes a risk-based approach with phased obligations, and a Mexican company offering products or services in that market may fall within its scope."),
        ("media", "video"),
        ("h2", "The four pillars of effective AI governance"),
        ("p", "A solid program does not start with a twenty-page policy, but with four practical decisions:"),
        ("ul", ["<strong>Transparency:</strong> document which models are used, what data they are trained on and which decisions they automate.",
                "<strong>Accountability:</strong> define who is responsible when a system fails or discriminates.",
                "<strong>Auditing:</strong> establish periodic reviews, both internal and external.",
                "<strong>Compliance:</strong> align every deployment with the applicable frameworks."]),
        ("quote", "The question is no longer whether your company needs AI governance, but when it will start building it."),
        ("h2", "The cost of inaction"),
        ("p", "Adopting AI without internal governance exposes a company to penalties, but also to <strong>loss of customer trust</strong>, <strong>stalled funding rounds</strong> and <strong>reputational risks</strong> that are hard to reverse."),
        ("h2", "Where to start"),
        ("p", "With an inventory of the AI systems in use, a classification by risk level, designated owners and alignment with standards such as ISO/IEC 42001 and the NIST AI Risk Management Framework. At BLIC we support tech companies and startups through that journey.")],
),
# ---------------------------------------------------------------- 2
dict(
    slug="lfpdppp-vs-gdpr", icon="fa-lock", cat=("Protección de Datos", "Data Protection"), fecha=(2026, 1, 8), mins=7,
    titulo=("LFPDPPP vs GDPR: lo que tu startup debe saber antes de escalar",
            "LFPDPPP vs GDPR: what your startup should know before scaling"),
    deck=("Comparativa práctica entre el marco mexicano y el europeo, y los errores más comunes al expandirse.",
          "A practical comparison of the Mexican and European frameworks, and the most common mistakes when expanding."),
    esencial=(["El GDPR puede aplicarte aunque no tengas oficinas en Europa.",
               "Ambos marcos giran en torno al consentimiento, la transparencia y los derechos de las personas.",
               "Conviene diseñar la privacidad desde el producto, no después de crecer."],
              ["The GDPR can apply to you even without an office in Europe.",
               "Both frameworks revolve around consent, transparency and individual rights.",
               "Privacy should be designed into the product, not added after growth."]),
    es=[("h2", "Dos marcos, una misma lógica"),
        ("p", "La Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP) y el Reglamento General de Protección de Datos (GDPR) comparten una base: tratar datos con una finalidad clara, informar a las personas y respetar sus derechos. La LFPDPPP fue renovada en 2025, y la autoridad en la materia pasó del extinto INAI a la Secretaría Anticorrupción y Buen Gobierno."),
        ("h2", "Dónde cambian las reglas"),
        ("ul", ["<strong>Alcance territorial:</strong> el GDPR puede aplicar a empresas fuera de la UE que ofrezcan bienes o servicios a personas en ese territorio.",
                "<strong>Bases de tratamiento:</strong> el GDPR reconoce varias bases legales además del consentimiento, como el interés legítimo o la ejecución de un contrato.",
                "<strong>Sanciones:</strong> el GDPR prevé multas que pueden alcanzar el 4 % de la facturación anual global o 20 millones de euros.",
                "<strong>Transferencias:</strong> enviar datos fuera de su jurisdicción exige mecanismos de protección específicos."]),
        ("media", "infografia"),
        ("quote", "Quien diseña la privacidad desde el producto no la paga dos veces."),
        ("h2", "Los errores más comunes al escalar"),
        ("p", "Copiar un aviso de privacidad de otra empresa, no mapear qué datos se recaban ni dónde viven, contratar proveedores en la nube sin cláusulas de protección de datos y no tener un procedimiento para atender solicitudes de las personas."),
        ("h2", "Qué hacer hoy"),
        ("p", "Elaborar un inventario de datos, revisar avisos y contratos con proveedores, y definir un responsable interno. Es una inversión pequeña frente al costo de corregirlo en plena ronda de inversión.")],
    en=[("h2", "Two frameworks, one logic"),
        ("p", "Mexico’s Federal Law on the Protection of Personal Data Held by Private Parties (LFPDPPP) and the EU General Data Protection Regulation (GDPR) share a foundation: process data for a clear purpose, inform individuals and respect their rights. The LFPDPPP was renewed in 2025, and the supervisory authority moved from the dissolved INAI to the Ministry of Anti-Corruption and Good Governance."),
        ("h2", "Where the rules differ"),
        ("ul", ["<strong>Territorial scope:</strong> the GDPR can apply to non-EU companies that offer goods or services to people in that territory.",
                "<strong>Legal bases:</strong> the GDPR recognizes several legal bases beyond consent, such as legitimate interest or contract performance.",
                "<strong>Penalties:</strong> the GDPR provides for fines of up to 4% of global annual turnover or €20 million.",
                "<strong>Transfers:</strong> sending data outside its jurisdiction requires specific safeguards."]),
        ("media", "infografia"),
        ("quote", "Those who design privacy into the product do not pay for it twice."),
        ("h2", "The most common mistakes when scaling"),
        ("p", "Copying another company’s privacy notice, failing to map what data is collected and where it lives, hiring cloud providers without data protection clauses, and having no procedure to handle requests from individuals."),
        ("h2", "What to do today"),
        ("p", "Build a data inventory, review notices and vendor contracts, and appoint an internal owner. It is a small investment compared with the cost of fixing it in the middle of a funding round.")],
),
# ---------------------------------------------------------------- 3
dict(
    slug="gobernanza-startups", icon="fa-scale-balanced", cat=("Gobernanza", "Governance"), fecha=(2026, 1, 3), mins=6,
    titulo=("Gobernanza corporativa para startups: cuándo formalizar y por qué",
            "Corporate governance for startups: when to formalize and why"),
    deck=("El momento exacto en que una startup debe profesionalizar su gobierno para no perder rondas de inversión.",
          "The exact moment a startup should professionalize its governance so it does not lose funding rounds."),
    esencial=(["La gobernanza no es burocracia: es la forma de tomar decisiones con reglas claras.",
               "Formalizar antes de la ronda reduce fricción y acelera la debida diligencia.",
               "Libros corporativos, acuerdos entre socios y cap table limpio son la base."],
              ["Governance is not bureaucracy: it is how decisions are made under clear rules.",
               "Formalizing before the round reduces friction and speeds up due diligence.",
               "Corporate books, shareholder agreements and a clean cap table are the foundation."]),
    es=[("h2", "El error de dejarlo para después"),
        ("p", "Muchas startups postergan su gobernanza porque “no es prioridad”. Hasta que llega un inversionista y pide actas, libro de socios, contratos de propiedad intelectual y un cap table consistente. Entonces lo urgente se vuelve cuello de botella."),
        ("media", "galeria"),
        ("h2", "Señales de que es momento de formalizar"),
        ("ul", ["Hay más de un socio y ninguna regla escrita sobre decisiones clave.",
                "Se contrató talento sin definir propiedad intelectual ni confidencialidad.",
                "Se está por abrir una ronda de capital o una alianza estratégica.",
                "La empresa empezó a operar en más de un país."]),
        ("quote", "La gobernanza no frena a una startup: le permite crecer sin improvisar."),
        ("h2", "Lo mínimo indispensable"),
        ("p", "Una estructura societaria adecuada al plan de negocio (por ejemplo, una SAPI en México cuando se anticipa inversión), estatutos y acuerdos entre socios, libros y actas al día, política de propiedad intelectual y un cap table verificable."),
        ("h2", "Gobernar sin volverse lento"),
        ("p", "El objetivo es sencillo: pocas reglas, claras y que se cumplan. Un consejo ligero, una cadencia de revisión trimestral y responsables definidos suelen bastar en etapas tempranas.")],
    en=[("h2", "The mistake of leaving it for later"),
        ("p", "Many startups postpone governance because it is “not a priority.” Until an investor arrives and asks for minutes, a shareholder ledger, intellectual property agreements and a consistent cap table. Then the urgent becomes a bottleneck."),
        ("media", "galeria"),
        ("h2", "Signs it is time to formalize"),
        ("ul", ["There is more than one founder and no written rules on key decisions.",
                "Talent was hired without defining intellectual property or confidentiality.",
                "A funding round or strategic alliance is about to open.",
                "The company has started operating in more than one country."]),
        ("quote", "Governance does not slow a startup down: it lets it grow without improvising."),
        ("h2", "The bare minimum"),
        ("p", "A corporate structure suited to the business plan (for example, a SAPI in Mexico when investment is anticipated), bylaws and shareholder agreements, up-to-date books and minutes, an intellectual property policy and a verifiable cap table."),
        ("h2", "Governing without slowing down"),
        ("p", "The goal is simple: few rules, clear and actually followed. A lean board, a quarterly review cadence and defined owners are usually enough in the early stages.")],
),
# ---------------------------------------------------------------- 4
dict(
    slug="propiedad-intelectual-digital", icon="fa-lightbulb", cat=("Propiedad Intelectual", "Intellectual Property"), fecha=(2025, 12, 28), mins=8,
    titulo=("Propiedad intelectual en la era digital: proteger lo intangible",
            "Intellectual property in the digital age: protecting the intangible"),
    deck=("Cómo proteger software, algoritmos y modelos de IA bajo el marco legal mexicano e internacional.",
          "How to protect software, algorithms and AI models under Mexican and international law."),
    esencial=(["El software se protege principalmente por derecho de autor; los algoritmos, con límites.",
               "El secreto industrial exige medidas reales de confidencialidad, no solo declaraciones.",
               "La titularidad se define por contrato desde el primer día."],
              ["Software is mainly protected by copyright; algorithms, within limits.",
               "Trade secrets require real confidentiality measures, not just statements.",
               "Ownership is defined by contract from day one."]),
    es=[("h2", "Lo intangible también tiene dueño"),
        ("p", "Para una empresa tecnológica, el código, los datos, las marcas y los modelos suelen valer más que sus activos físicos. Protegerlos exige combinar distintas figuras, porque ninguna cubre todo."),
        ("h2", "Qué figura protege qué"),
        ("ul", ["<strong>Derecho de autor:</strong> protege el software como obra, incluido su código fuente y objeto.",
                "<strong>Marcas:</strong> protegen el nombre y los signos distintivos de la solución.",
                "<strong>Patentes:</strong> pueden proteger invenciones técnicas, aunque los programas de cómputo y los algoritmos en sí enfrentan límites.",
                "<strong>Secreto industrial:</strong> protege información confidencial con valor competitivo, siempre que se tomen medidas para mantenerla en reserva."]),
        ("media", "infografia"),
        ("quote", "Lo que no está en un contrato, difícilmente será tuyo cuando más lo necesites."),
        ("h2", "El punto ciego: la titularidad"),
        ("p", "Muchos conflictos nacen de preguntas simples. ¿Quién es dueño del código escrito por un freelancer? ¿Y el modelo entrenado con datos de un cliente? Cesiones de derechos, cláusulas de confidencialidad y acuerdos con desarrolladores deben firmarse antes de empezar a construir."),
        ("h2", "IA generativa: nuevas preguntas"),
        ("p", "El uso de modelos de IA plantea retos sobre autoría de los resultados y sobre los datos con los que se entrena. Se trata de un terreno en evolución, por lo que conviene documentar las fuentes y revisar los términos de las herramientas utilizadas.")],
    en=[("h2", "The intangible has an owner too"),
        ("p", "For a technology company, code, data, trademarks and models are often worth more than physical assets. Protecting them requires combining different legal tools, because none covers everything."),
        ("h2", "Which tool protects what"),
        ("ul", ["<strong>Copyright:</strong> protects software as a work, including source and object code.",
                "<strong>Trademarks:</strong> protect the name and distinctive signs of the solution.",
                "<strong>Patents:</strong> can protect technical inventions, although computer programs and algorithms as such face limits.",
                "<strong>Trade secrets:</strong> protect confidential information with competitive value, as long as measures are taken to keep it secret."]),
        ("media", "infografia"),
        ("quote", "What is not in a contract will hardly be yours when you need it most."),
        ("h2", "The blind spot: ownership"),
        ("p", "Many disputes begin with simple questions. Who owns the code written by a freelancer? And the model trained on a client’s data? Assignments of rights, confidentiality clauses and agreements with developers must be signed before building begins."),
        ("h2", "Generative AI: new questions"),
        ("p", "Using AI models raises challenges around authorship of the outputs and the data used for training. This is an evolving field, so it is wise to document sources and review the terms of the tools used.")],
),
# ---------------------------------------------------------------- 5
dict(
    slug="compliance-ventaja-competitiva", icon="fa-shield-halved", cat=("Compliance", "Compliance"), fecha=(2025, 12, 20), mins=5,
    titulo=("Compliance regulatorio: de la obligación a la ventaja competitiva",
            "Regulatory compliance: from obligation to competitive advantage"),
    deck=("Por qué las empresas que invierten en cumplimiento cierran mejores rondas y escalan más rápido.",
          "Why companies that invest in compliance close better rounds and scale faster."),
    esencial=(["El compliance bien hecho reduce riesgo y también acelera ventas e inversión.",
               "Un programa funcional es proporcional al tamaño y al riesgo de la empresa.",
               "Medir y documentar es tan importante como tener políticas."],
              ["Well-run compliance reduces risk and also speeds up sales and investment.",
               "A working program is proportionate to the company’s size and risk.",
               "Measuring and documenting matters as much as having policies."]),
    es=[("h2", "Más que evitar multas"),
        ("p", "Durante años el compliance se vio como un costo: algo que se hace para no ser sancionado. Hoy es un criterio de decisión. Grandes clientes, bancos e inversionistas piden evidencia de que una empresa gestiona sus riesgos antes de firmar."),
        ("h2", "Qué componentes tiene un programa funcional"),
        ("ul", ["Mapa de riesgos regulatorios del negocio.",
                "Políticas claras y comprensibles, no solo extensas.",
                "Capacitación periódica y canal de denuncia.",
                "Monitoreo, indicadores y revisión continua."]),
        ("quote", "Un programa que nadie entiende es papel; uno que se mide es una ventaja."),
        ("media", "video"),
        ("h2", "El efecto en la inversión"),
        ("p", "En la debida diligencia, un historial ordenado de cumplimiento acorta tiempos y reduce contingencias que de otro modo se traducen en descuentos de valuación o condiciones suspensivas."),
        ("h2", "Cómo empezar sin paralizarse"),
        ("p", "Priorizar por riesgo: identificar las tres obligaciones con mayor impacto para el negocio y resolverlas primero. El compliance se construye por capas, no de un solo golpe.")],
    en=[("h2", "More than avoiding fines"),
        ("p", "For years compliance was seen as a cost: something done to avoid penalties. Today it is a decision criterion. Large customers, banks and investors ask for evidence that a company manages its risks before they sign."),
        ("h2", "What a working program includes"),
        ("ul", ["A map of the business’s regulatory risks.",
                "Clear, understandable policies, not merely lengthy ones.",
                "Regular training and a reporting channel.",
                "Monitoring, indicators and continuous review."]),
        ("quote", "A program nobody understands is paper; one that is measured is an advantage."),
        ("media", "video"),
        ("h2", "The effect on investment"),
        ("p", "In due diligence, an orderly compliance record shortens timelines and reduces contingencies that would otherwise turn into valuation discounts or conditions precedent."),
        ("h2", "How to start without freezing up"),
        ("p", "Prioritize by risk: identify the three obligations with the greatest impact on the business and resolve them first. Compliance is built in layers, not all at once.")],
),
# ---------------------------------------------------------------- 6
dict(
    slug="contratos-internacionales", icon="fa-file-contract", cat=("Contratos", "Contracts"), fecha=(2025, 12, 15), mins=6,
    titulo=("Contratos internacionales: errores comunes al cruzar fronteras",
            "International contracts: common mistakes when crossing borders"),
    deck=("Las cláusulas que salvan negociaciones y las que las hunden cuando operas entre México y Estados Unidos.",
          "The clauses that save negotiations and the ones that sink them when you operate between Mexico and the United States."),
    esencial=(["Ley aplicable y jurisdicción deben pensarse en función de dónde se ejecutará el contrato.",
               "El arbitraje suele facilitar la ejecución de resoluciones en varios países.",
               "Los detalles operativos (moneda, idioma, impuestos) también son cláusulas críticas."],
              ["Governing law and jurisdiction should be chosen based on where the contract will be enforced.",
               "Arbitration often makes it easier to enforce decisions across several countries.",
               "Operational details (currency, language, taxes) are critical clauses too."]),
    es=[("h2", "Un contrato no viaja solo"),
        ("p", "Un contrato firmado en un país puede tener que cumplirse, interpretarse o ejecutarse en otro. Cuando las partes operan entre México y Estados Unidos, las diferencias entre sistemas jurídicos pueden convertir una cláusula inocente en un conflicto costoso."),
        ("h2", "Las cláusulas que más se descuidan"),
        ("ul", ["<strong>Ley aplicable:</strong> qué derecho interpreta el contrato.",
                "<strong>Jurisdicción o arbitraje:</strong> dónde y cómo se resolverán las controversias.",
                "<strong>Idioma:</strong> qué versión prevalece si existen traducciones.",
                "<strong>Moneda y pagos:</strong> tipo de cambio, impuestos y retenciones.",
                "<strong>Terminación:</strong> causas, avisos y consecuencias."]),
        ("quote", "El mejor contrato es el que ambas partes pueden ejecutar sin necesidad de abogados."),
        ("media", "galeria"),
        ("h2", "Arbitraje frente a tribunales"),
        ("p", "Para operaciones transfronterizas, el arbitraje suele ofrecer mayor neutralidad y facilidad de ejecución, ya que México y Estados Unidos son parte de la Convención de Nueva York sobre reconocimiento de laudos. Aun así, cada caso exige analizar costos, tiempos y el tipo de relación comercial."),
        ("h2", "Una lista antes de firmar"),
        ("p", "Verificar facultades de los firmantes, confirmar que la entidad contratante existe y es solvente, revisar anexos y definiciones, y pedir que un abogado conozca ambos entornos legales antes de aceptar un modelo ajeno.")],
    en=[("h2", "A contract does not travel alone"),
        ("p", "A contract signed in one country may have to be performed, interpreted or enforced in another. When the parties operate between Mexico and the United States, differences between legal systems can turn an innocent clause into a costly dispute."),
        ("h2", "The most overlooked clauses"),
        ("ul", ["<strong>Governing law:</strong> which law interprets the contract.",
                "<strong>Jurisdiction or arbitration:</strong> where and how disputes will be resolved.",
                "<strong>Language:</strong> which version prevails if translations exist.",
                "<strong>Currency and payments:</strong> exchange rate, taxes and withholdings.",
                "<strong>Termination:</strong> grounds, notices and consequences."]),
        ("quote", "The best contract is the one both parties can perform without needing lawyers."),
        ("media", "galeria"),
        ("h2", "Arbitration versus courts"),
        ("p", "For cross-border transactions, arbitration usually offers greater neutrality and easier enforcement, since Mexico and the United States are parties to the New York Convention on the recognition of arbitral awards. Even so, each case requires weighing costs, timing and the type of commercial relationship."),
        ("h2", "A checklist before signing"),
        ("p", "Verify the signatories’ authority, confirm the contracting entity exists and is solvent, review annexes and definitions, and have a lawyer who knows both legal environments review any model contract you did not draft.")],
),
]

AUTORA = dict(
    nombre="Gabriela L. González Vázquez",
    rol=("Abogada Corporativa & Compliance", "Corporate & Compliance Attorney"),
    bio=("Más de 12 años de experiencia en gobernanza corporativa, compliance y regulación tecnológica. Gerente de Gobernanza Corporativa, Tech y Cumplimiento Digital en BLIC.",
         "Over 12 years of experience in corporate governance, compliance and technology regulation. Corporate Governance, Tech & Digital Compliance Manager at BLIC."),
    foto="assets/autora-gabriela.jpg",
    foto_respaldo="assets/foto-sobre-mi.jpg",
)
